version: '3'

services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=https://obohdaxvawmjhxsjgikp.supabase.co
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - EDGE_FUNCTION_URL=https://obohdaxvawmjhxsjgikp.supabase.co/functions/v1
    restart: always
