version: '3.8'

services:
  postgres-dev:
    image: postgres:15
    container_name: portal_dr_marcio_db_dev
    environment:
      POSTGRES_DB: portal_dr_marcio_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
