[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'dumb-init']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'dumb-init npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'true'
